### ISSUE TITLE
setup.py doesn't declare the requirements of Azure or GCP

### ISSUE THREAD

**Issue by psav** [project-koku/nise#145]

**Comment by lcouzens** [comment]
@adberglund 
I added Priority high to this as while fixing the smoke/stable e2e run this is now causing my provider tests that use nise to fail. Could we possible fix this one soon ish?

**Comment by maskarb** [comment]
@lcouzens  Just merged PR for this fix.

**Comment by dccurtis** [comment]
@maskarb Different problem.  You added the nise module.  This is for the azure and google sdks themself.  The test automation isn't able to update a Pipenv basically and they need to be installed when nise itself is installed

**Comment by lcouzens** [comment]
So I believe this is working correctly now.
