### ISSUE TITLE
Ability to generate OpenShift on Azure data

### ISSUE THREAD

**Issue by adberglund** [project-koku/nise#163]
## User Story
As a developer or QE engineer, I would like the ability to generate OpenShift and Azure data such that OpenShift on Azure matching can be tested.

## Assumptions and Information
- We probably want an option for OpenShift data to indicate what underlying infrastructure the cluster is "on". This would probably translate to a command line arg to specify if we want OpenShift AWS data or OpenShift Azure data (and other sources as they are supported).
- See https://drive.google.com/drive/u/1/folders/1OZbbyvWRjii63QBFDhnatOUZA9_KGs_E for actual OpenShift on Azure data

## Acceptance Criteria
- [ ] Both Azure and OpenShift can use the same tag keys (for tag matching)
- [ ] Azure tags accept `openshift_cluster` `openshift_node` and `openshift_project` tag keys
- [ ] The OpenShift node name should match the portion of the Azure InstanceID after the last `/` (e.g. OpenShift node: `costmgmtacct1234`; Azure InstanceID: `Microsoft.Compute/virtualMachines,subscriptions/1327506759515/resourceGroups/RG2/providers/Microsoft.Compute/virtualMachine/costmgmtacct1234`
~- [ ] The OpenShift node name should match the resource_id when generating OpenShift on Azure data~
- [ ] The examples directory has example static yaml files

**Comment by lcouzens** [comment]
Verified
