### ISSUE TITLE
Azure tags use AWS format

### ISSUE THREAD

**Issue by adberglund** [project-koku/nise#169]
## Summary
When creating a nise Azure report file it creates tags using the AWS tag prefix. We should fix this.

Ex. 

`{"resourceTags/user:storageclass": "charlie"}` is being generated, but the expected output should be `{"storageclass": "charlie"}` -- no prefix.

This is probably a problem with the example YAML for OpenShift on Azure. We should just update the YAMLs to have the right style of tags. 

 - [ ] Reload proper data in CI and prod demo accounts for Azure so bad tags aren't there.

**Comment by lcouzens** [comment]
Verified!
