### ISSUE TITLE
[AWS] Regions and Availability Zones are different things.

### ISSUE THREAD

**Issue by blentz** [project-koku/nise#171]
AWS distinguishes between regions and availability zones.

A single region (e.g. `us-east-1`) can have multiple availability zones (e.g. `us-east-1a`, `us-east-1b`, `us-east-1c`).

Nise currently uses the label "Region" to refer to Availability Zones. This needs to be corrected so that we apply the correct label to the appropriate objects.

Example: https://github.com/project-koku/nise/blob/master/examples/ocp_on_aws/aws_static_data.yml#L9

**Comment by adberglund** [comment]
Check that this is an inconsistency with the cost and usage format that nise is based on. If so correct. If this is in-line with the CUR then perhaps we leave it as is? 

Also this may just be a typo in the static file: we can just remove the availability zone off of the region. -- Check the code to see if region handling is a problem there.

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Andrew: "In the example, my question here is what is the cost-and-usage-report say? Does it return both region and zone? This effectively hurts nothing except for readability."

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-115
