### ISSUE TITLE
the exact package pins in the actual package limit use in other ecosystems

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [project-koku/nise#179]
without context, the pins in `setup.py` seem needlessly exact,
this creates issues when trying to use the package in the insights testing ecosystem as it hampers our ability to pin dependencies (pypa/pip#988 applies)

https://github.com/project-koku/nise/blob/b5a0c65305c1ca8c443b6f116966b704649a91f1/setup.py#L23-L69

i'm happy to provide a patch weakening them once its understood why it was  pinned so tightly

**Comment by blentz** [comment]
@RonnyPfannschmidt - We don't have a strong need for such exact requirements. A patch to open them up to at least minor version updates (e.g. `"azure-common~=1.1"`) would be welcome.

**Comment by blentz** [comment]
This has been fixed in PR #181 .
