### ISSUE TITLE
Static files should not require every parameter to be defined

### ISSUE THREAD

**Issue by blentz** [project-koku/nise#191]
## User Story
As a Nise user creating a static file, 
I want to only specify the options that should be set statically,
So that I can write simpler static files that only include the details that I care about and allows all other values to be randomly generated.

## Assumptions 
- Currently when a field is not defined it is set to `None`
- We would want a random value filled instead

## Acceptance Criteria 
- [ ] An "incomplete" static file still produces a report with meaningful values. 
- [ ] Values that were `None` are now a random value with the correct data type.

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:
Brett: for context, in the generators if you omit any field it's set to None, so this will need work to not set things to None if they're not defined.
Andrew: You should still get a meaningful report, data type matters with these files so that might add complexity.

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-109
