### ISSUE TITLE
Generate multiple files

### ISSUE THREAD

**Issue by adberglund** [project-koku/nise#198]
## User Story
As a developer or quality engineer running performance testing I want multiple files to be created so that we mirror our real sources and data is dumped to file before nise runs out of memory.

## Assumptions
- When writing data off to a file we probably want to batch the operation and close and open a new file after a certain number of rows
- We need the file size to be no greater than 100MB (an env configurable value?) to respect the Platform Ingress service's upper limit.  

## Acceptance Criteria

- [ ] nise doesn't OOM
- [ ] nise creates multiple files

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

OOM = Out of Memory
