### ISSUE TITLE
Negative values in unused capacity and unrequested capacity

### ISSUE THREAD

**Issue by chargio** [project-koku/nise#224]
When accessing the OpenShift details, grouped by cluster, you can see negative unused capacity and unrequested capacity.

![image](https://user-images.githubusercontent.com/7500590/80619007-654a5180-8a44-11ea-88cb-ee7f510acc17.png)

**Comment by chargio** [comment]
I've seen in a customer meeting today that the numbers look like we are showing the percentage is the used one, not the unused (based on the way we were showing the graphic). It would be great to review what we are showing here

**Comment by chargio** [comment]
Same example: CPU
![image](https://user-images.githubusercontent.com/7500590/80727606-35638280-8b06-11ea-8292-ebfa86af938f.png)

You can see that the grey are goes close the top, but we are telling the customer that unused capacity is 85% of it, instead of 15%)

**Comment by adberglund** [comment]
I think we need to check our math in nise to make sure that usage/requests aren't able to go above capacity.

**Comment by adberglund** [comment]
Opened as https://issues.redhat.com/browse/COST-82
