### ISSUE TITLE
Add more services to AWS data generator

### ISSUE THREAD

**Issue by lcouzens** [project-koku/nise#50]
Currently it seems we only have AmazonEC2, When using the data for automated tests it would be useful to have mother services to filter with.

        {
            "date": "2018-11-21",
            "services": [
                {
                    "service": "AmazonEC2",
                    "values": [
                        {
                            "date": "2018-11-21",
                            "units": "USD",
                            "service": "AmazonEC2",
                            "total": 2929.778618413
                        }
                    ]
                }
            ]
        },
        {
            "date": "2018-11-22",
            "services": [
                {
                    "service": "AmazonEC2",
                    "values": [
                        {
                            "date": "2018-11-22",
                            "units": "USD",
                            "service": "AmazonEC2",
                            "total": 3305.474909326

**Comment by dccurtis** [comment]
nise has generators for EBS, EC2, S3, and data_transfer.

All of those generators have the following:
`row['lineItem/ProductCode'] = 'AmazonEC2'`
`row['product/servicecode'] = 'AmazonEC2'` (data_transfer is the exception to this one)

**Comment by dccurtis** [comment]
After studying some real AWS data, it looks like the S3 generator is really the only one that has incorrect `ProductCode` and `servicecode`
