### ISSUE TITLE
RFE: Generate account alias with static AWS reports

### ISSUE THREAD

**Issue by lcouzens** [project-koku/nise#80]
It would be great to have the ability to set account alias when generating static AWS reports. Correct me if I am wrong but I don't think we support that currently.

**Comment by dccurtis** [comment]
The cluster alias is not part of the cost and usage report.  Masu gets it by doing a separate API call which updates a table in the database.

I wouldn't be helpful for testing the masu AWS alias updating; but we could add a test endpoint which could be used to set the values in the database.
