### ISSUE TITLE
Create OpenShift on AWS datasets with Network, Storage, and Database cost

### ISSUE THREAD

**Issue by chambridge** [project-koku/nise#98]
In order to demo and preview all the data across all the existing data types we need sample OpenShift and AWS static data templates.

The static data templates should use the resource ID correlation to link the Openshift Data with the AWS data.

The static data templates should allow for cost distribution using tags on `openshift_cluster`, `openshift_project`, `openshift_node` basis where applicable.

The kind of data that needs to be captured are those services/product families that will populate the Database, Storage, and Networking cards.

Networking - VPC, Load Balancer, etc
Storage - S3, Glacier, etc
Database - RDS, Elastic, etc

**Comment by adberglund** [comment]
@lcouzens Again, not sure there's anything to test on this one as it was just creating the Summit demo data. But the product of the work was the nise examples folder with a fairly detailed static report file for OCP on AWS.
